name: Test

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'

env:
  NODE_VERSION: '24.21.0'

jobs:

  cli:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run CLI
        run: npm exec . -- --projectName test-islands --frameworks react

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  format-docs:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Run format
        working-directory: docs
        run: npm run format

  format-integrations:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: integrations
        run: npm ci

      - name: Run format
        working-directory: integrations
        run: npm run format

  format:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: template
        run: npm ci

      - name: Run format
        working-directory: template
        run: npm run format

  lint-docs:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Run lint
        working-directory: docs
        run: npm run lint

  lint-integrations:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: integrations
        run: npm ci

      - name: Run lint
        working-directory: integrations
        run: npm run lint

  lint:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: template
        run: npm ci

      - name: Run lint
        working-directory: template
        run: npm run lint

  framework-all:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro
          --projectName test-islands
          --frameworks angular
          --frameworks preact
          --frameworks qwik
          --frameworks react
          --frameworks solid
          --frameworks svelte
          --frameworks vanilla
          --frameworks vue

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-angular:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks angular

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output


  framework-preact:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks preact

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-qwik:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks qwik

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-react:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks react

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-solid:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks solid

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-svelte:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks svelte

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-vanilla:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks vanilla

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  framework-vue:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        run: npm ci

      - name: Run CLI
        run: npx create-outsystems-astro --projectName test-islands --frameworks vue

      - name: Run output
        working-directory: test-islands
        run: npm ci && npm run output

  security-docs:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: docs
        run: npm ci

      - name: Run security check
        working-directory: docs
        run: npm run audit

  security-integrations:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: integrations
        run: npm ci

      - name: Run security check
        working-directory: integrations
        run: npm run audit

  security-main:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
        
      - name: Install dependencies
        run: npm ci

      - name: Run security check
        run: npm audit

  security-template:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: template
        run: npm ci

      - name: Run security check
        working-directory: template
        run: npm run audit

  test:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: template
        run: npm ci

      - name: Run tests
        working-directory: template
        run: npm run test

  teste2e:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: template
        run: npm ci

      - name: Install Playwright
        working-directory: template
        run: npm run test:e2e:install

      - name: Run tests
        working-directory: template
        run: npm run test:e2e

  typecheck:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code
        uses: actions/checkout@v7.0.1

      - name: Use Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build integrations
        working-directory: integrations
        run: npm ci && npm run process

      - name: Install dependencies
        working-directory: template
        run: npm ci

      - name: Run type check
        working-directory: template
        run: npm run typecheck
